### ISSUE TITLE
Upload assets to an existing release in CI [My way]

### ISSUE THREAD

**Issue by Unike267** [Unike267/Thesis#1]
## Upload assets in CI my way:

To upload files associated to an existing release in Continuous Integration I follow the following steps:

- Generate a tag associated with a commit in the local repository:
  - `git tag -a tag_name -m "tag message"` (last commit)
  - Extra info:
    -  `git tag tag_name commit_hash` (for a specific commit)
    - `git tag -d tag_name` (to delete a tag)
- Push the tag to the remote repository:
  - `git push origin tag_name` 
- Create a new release through the GitHub API from the tag you created.
  - This release will contain as default assets the compressed source code.
- To upload your custom assets through CI to an existing release, please note the following consideration:
  - At the beginning of the YML file the following must be specified:

```yml
on:
  #your configuration
  release:
    types:
      - published

permissions:
  contents: write
```

-  And then add the following step inside your job/jobs:

``` yml
      - name: '📤 Upload Release Assets'
        run: gh release upload --repo OWNER/REPO --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: # Release TAG
          FILES: # The asset path (The path where the file you want to attach to the release is located)
```

**This way uses directly the [GitHub CLI](https://cli.github.com/manual/gh_release_upload).**

Instead of this way you can use the **GH actions**, BUT:

![warning_2](https://github.com/user-attachments/assets/5339592e-859b-41f7-b38c-b9853293c25d)

<p align="center"> 
<strong> This mode does not allow overwriting of assets !</strong>
</p>

- For this purpose add the following step inside your job/jobs:

``` yml
      - name: '📤 Upload Release Asset'
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: # The realese URL (Explanation of how to know this url below)
          asset_path: # The asset path (The path where the file you want to attach to the release is located)
          asset_name: # The asset name (Including file extension)
          asset_content_type: # Asset content type
``` 
- How to know the **upload_url**?
  - Generate new token through GitHub API in: `https://github.com/settings/tokens` (Clasic; only selected repo).
  - Apply the following command in the terminal:

``` bash
curl -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer NEWLY_GENERATED_TOKEN"   -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/OWNER/REPO/releases/tags/TAG
```
-
  - Copy the  **upload_url** and paste in the YML file.
  - Will have a structure similar to:
    - ` "upload_url": https://uploads.github.com/repos/OWNER/REPO/releases/THE_NUMBER_WE_ARE_INTERESRED_IN/assets{?name,label}` 
    - The assets is directly like this: `assets{?name,label}`

## To delete an asset from the release

With the above considerations add the following step:

``` yml
      - name: '⚠️ DELETE Release Assets'
        run: gh delete-asset --yes --repo OWNER/REPO $TAG $NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: # Release TAG
          NAME: # Asset name
```

Or use GitHub actions: 

```yml
      - name: '⚠️ DELETE Release Assets'
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: # Release TAG
          repository: # OWNER/REPO
          assets: # The file to be deleted
```

**Comment by Unike267** [comment]
To solve:

![Thesis_issue_1](https://github.com/user-attachments/assets/bda12bee-1b6e-4e76-8b40-9c6dbdcefb7b)

Try to apply:

```yml
      - name: #Step Name
        uses: #Step action
        with:
          node-version: '18'
```
